name: Build & Deploy

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is merged to main
        id: pr-merged-check
        run: echo "::set-output name=merged::$(if [[ ${{ github.event_name }} == 'pull_request' && ${{ github.event.pull_request.base.ref }} == 'main' && ${{ github.event.pull_request.merged }} == 'true' ]]; then echo true; else echo false; fi)"

      - name: Deploy Bootstrap 5 static webpage for my-site
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            if [ "${{ steps.pr-merged-check.outputs.merged }}" == "true" ]; then
              cd /var/www/my-site
              git pull
              echo 'Deployment successful to Digital Ocean'
            else
              echo 'Not a merged pull request to main; deployment skipped'
            fi
